# Generated by Django 4.0.6 on 2022-07-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_alter_contactus_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(default=1234567890)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_of_event',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
